import { Application, Request, Response } from "express";
import { log } from "../middlewares/log";
import { response } from "./../utils/response";

import cdmRoutes from "./cdm";
import departmentRoutes from "./department";
import productRoutes from "./product";
import priceSuggestionRoutes from "./priceSuggestion";
import priceQueueRoutes from "./priceQueue";
import priceAnalisysRoutes from "./priceAnalisys";
import priceSuggestionHistoryRoutes from "./priceSuggestionHistory";
import profileRoutes from "./profile";
import attributeRoutes from "./attribute";
import atributeGroupAttributeRoutes from "./attributeGroupAttribute";
import productAttributeValueRoutes from "./productAttributeValue";
import attributeGroupRoutes from "./attributeGroup";
import bannersSlidersRoutes from "./bannersSliders";
import userRoutes from "./user";
import orderRoutes from "./order";
import carrierRoutes from "./carrier";
import carrierChannelRoutes from "./carrier-channel";
import fileDownloadRoutes from "./fileDownload";
import favoriteSkuRoutes from "./favoriteSkus";
import skuObservationRoutes from "./skuObservations";
import ticketRoutes from "./ticket";
import ticketStatusRoutes from "./ticketStatus";
import ticketPriorityLevelRoutes from "./ticketPriorityLevel";
import ticketHistoryRoutes from "./ticketHistory";
import ticketChatsRoutes from "./ticketChat";
import webPriceRoutes from "./webPrice";
import abandonedCarts from "./abandonedCarts";
import productCostRoutes from "./productCost";
import googleMerchantRoutes from "./google-merchant";
import productFeedRoutes from "./productFeed";
import feedRoutes from "./feed";
import productFeedHistoryRoutes from "./productFeedHistory";
import { checkToken } from "../middlewares/checkToken";
import productFeedCustomLabel from "./productFeedCustomLabel";
import productFeedCustomLabelGen from "./productFeedCustomLabelGen";
import mlistingRoutes from "./mlisting";
import salesRules from "./salesRules";
import coupons from "./coupons";
import mlScraperRoutes from "./mlScraper";
import mlapiRoutes from "./mlapi";
import googleProductRoutes from "./googleProduct";
import SkuRecommendationRoutes from "./skuRecommendation";
import productStockRoutes from "./productStock";
import metaNotificationRoutes from "./metaNotification";
import taxInstallmentRoutes from "./taxInstallment";
import priceRuleRoutes from "./priceRule";
import controllerFilaPubExec from "./controllerFilaPubExec";
import pendingPublicationRouter from "./pendingPublication";
import orderTracking from "./orderTracking";
import orderNewStatus from "./orderTrackingNewStatus";
import accessRoutes from "./access";
import storeFrontRoutes from "./storeFront";
import epriceRoutes from "./eprice";

export default (app: Application) => {
  app.all("/", log, async (req: Request, res: Response) => {
    response(res, 200, "OK");
  });

  app.use("/user", log, userRoutes);
  app.use("/profile", log, profileRoutes);
  app.use("/department", log, checkToken, departmentRoutes);
  app.use("/order", log, checkToken, orderRoutes);
  app.use("/order-tracking", log, checkToken, orderTracking);
  app.use("/order-new-status", log, checkToken, orderNewStatus);
  app.use("/product", log, checkToken, productRoutes);
  app.use("/favorite-sku", log, checkToken, favoriteSkuRoutes);
  app.use("/sku-observation", log, checkToken, skuObservationRoutes);
  app.use("/price-suggestion", log, checkToken, priceSuggestionRoutes);
  app.use("/price-analisys", log, checkToken, priceAnalisysRoutes);
  app.use("/price-suggestion-history", log, checkToken, priceSuggestionHistoryRoutes);
  app.use("/price-queue", log, checkToken, priceQueueRoutes);
  app.use("/assembly-center", log, cdmRoutes);
  app.use("/file-download", log, fileDownloadRoutes);
  app.use("/banner-slider", log, checkToken, bannersSlidersRoutes);
  app.use("/carrier", log, checkToken, carrierRoutes);
  app.use("/carrier-channel", log, checkToken, carrierChannelRoutes);
  app.use("/attribute", log, checkToken, attributeRoutes);
  app.use("/attribute-value", log, checkToken, productAttributeValueRoutes);
  app.use("/attribute-group", log, checkToken, attributeGroupRoutes);
  app.use("/attribute-group-attribute", log, checkToken, atributeGroupAttributeRoutes);
  app.use("/ticket", log, checkToken, ticketRoutes);
  app.use("/ticket-status", log, checkToken, ticketStatusRoutes);
  app.use("/ticket-priority-level", log, checkToken, ticketPriorityLevelRoutes);
  app.use("/ticket-history", log, checkToken, ticketHistoryRoutes);
  app.use("/ticket-chat", log, checkToken, ticketChatsRoutes);
  app.use("/web-price", log, checkToken, webPriceRoutes);
  app.use("/abandoned-carts", log, checkToken, abandonedCarts);
  app.use("/product-cost", log, checkToken, productCostRoutes);
  app.use("/google-merchant", log, checkToken, googleMerchantRoutes);
  app.use("/product-feed", log, checkToken, productFeedRoutes);
  app.use("/feed", log, checkToken, feedRoutes);
  app.use("/product-feed-history", log, checkToken, productFeedHistoryRoutes);
  app.use("/product-feed-custom-label", log, checkToken, productFeedCustomLabel);
  app.use("/product-feed-custom-label-gen", log, checkToken, productFeedCustomLabelGen);
  app.use("/mlisting", log, checkToken, mlistingRoutes);
  app.use("/sales-rules", log, checkToken, salesRules);
  app.use("/coupons", log, checkToken, coupons);
  app.use("/ml-scraper", log, checkToken, mlScraperRoutes);
  app.use("/mlapi", log, checkToken, mlapiRoutes);
  app.use("/google-product", log, checkToken, googleProductRoutes);
  app.use("/sku-recommendation", log, checkToken, SkuRecommendationRoutes);
  app.use("/product-stock", log, checkToken, productStockRoutes);
  app.use("/notification", log, checkToken, metaNotificationRoutes);
  app.use("/tax-installment", log, checkToken, taxInstallmentRoutes);
  app.use("/price-rule", log, checkToken, priceRuleRoutes);
  app.use("/controller-fila-pub-exec", log, checkToken, controllerFilaPubExec);
  app.use("/pendingPublication", log, checkToken, pendingPublicationRouter);
  app.use("/access", log, checkToken, accessRoutes);
  app.use("/storefront", log, checkToken, storeFrontRoutes);
  app.use("/eprice", log, epriceRoutes);
};
